backend:
  name: "git-gateway"
  branch: "master"
  repo: "cefafortaleza/website"
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/horarios/index.md"
        label: "Horários"
        name: "horarios"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "horarios",
            }
          - {
              label: "Horários da Semana",
              name: "horarios",
              widget: "object",
              create: true,
              fields:
                [
                  {
                    label: "Dia da Semana",
                    name: "dayname",
                    widget: "string",
                    default: "Domingo",
                  },
                  {
                    label: "Horários - Manhã",
                    name: "morning",
                    widget: "list",
                    create: true,
                    fields:
                      [
                        {
                          label: "Nome",
                          name: "name",
                          widget: "string",
                          default: "Manhã",
                        },
                        { label: "Horário", name: "time", widget: "string" },
                        {
                          label: "Descrição",
                          name: "description",
                          widget: "string",
                        },
                      ],
                  },
                  {
                    label: "Horários - Tarde",
                    name: "afternoon",
                    widget: "list",
                    create: true,
                    fields:
                      [
                        {
                          label: "Nome",
                          name: "name",
                          widget: "hidden",
                          default: "Tarde",
                        },
                        {
                          label: "Horário",
                          name: "time",
                          widget: "datetime",
                          time_format: "HH:mm",
                          format: "LT",
                        },
                        {
                          label: "Descrição",
                          name: "description",
                          widget: "string",
                        },
                      ],
                  },
                  {
                    label: "Horários - Noite",
                    name: "evening",
                    widget: "list",
                    create: true,
                    fields:
                      [
                        {
                          label: "Nome",
                          name: "name",
                          widget: "hidden",
                          default: "Noite",
                        },
                        {
                          label: "Horário",
                          name: "time",
                          widget: "datetime",
                          time_format: "HH:mm",
                          format: "LT",
                        },
                        {
                          label: "Descrição",
                          name: "description",
                          widget: "string",
                        },
                      ],
                  },
                ],
            }

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Slides",
              name: "mainslides",
              widget: "list",
              create: true,
              fields:
                [
                  {
                    label: "Slide",
                    name: "slide",
                    widget: "object",
                    fields:
                      [
                        { label: "Frase", name: "frase", widget: "string" },
                        { label: "Autor", name: "autor", widget: "string" },
                        {
                          label: "Background",
                          name: "background",
                          widget: "image",
                        },
                        {
                          label: "Alinhamento do Texto",
                          name: "align",
                          widget: "select",
                          options:
                            [
                              { label: "À esquerda", value: "left" },
                              { label: "Centralizado", value: "center" },
                              { label: "À direita", value: "right" },
                            ],
                        },
                        {
                          label: "Cor do Texto",
                          name: "color",
                          widget: "select",
                          options:
                            [
                              { label: "Branco", value: "white" },
                              { label: "Preto", value: "black" },
                            ],
                        },
                        {
                          label: "Botão 1 - Link",
                          name: "primeiro_botao_link",
                          widget: "string",
                        },
                        {
                          label: "Botão 1 - Texto",
                          name: "primeiro_botao_texto",
                          widget: "string",
                        },
                        {
                          label: "Botão 2 - Link",
                          name: "segundo_botao_link",
                          widget: "string",
                        },
                        {
                          label: "Botão 2 - Texto",
                          name: "segundo_botao_texto",
                          widget: "string",
                        },
                      ],
                  },
                ],
            }

      - file: "src/pages/sobre/index.md"
        label: "Sobre o CEFA"
        name: "sobre"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Arquivo de Estatuto",
              name: "bylaws",
              widget: "file",
              default: "static/ESTATUTO.pdf",
            }
          - {
              label: "Arquivo de Política Interna",
              name: "internalPolicyLink",
              widget: "file",
              default: "static/REGIMENTO.docx",
            }
          - { label: "phoneNumber", name: "phoneNumber", "widget": "string" }
          - { label: "email", name: "email", widget: "string" }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    fields:
      - {
          name: "templatekey",
          label: "Template Key",
          widget: "hidden",
          default: "blog-post",
        }
      - { name: "path", label: "Path" }
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "featuredpost", label: "Featured Post", widget: "boolean" }
      - { name: "featuredImage", label: "Image", widget: "img" }
      - { name: "body", label: "Body", widget: "markdown" }
