backend:
  name: git-gateway
  branch: master
  repo: cefafortaleza/website
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/espiritismo/index.md'
        label: 'Sobre o espiritismo'
        name: 'espiritismo'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'sobre-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - file: 'src/pages/sobre/index.md'
        label: 'Sobre o CEFA'
        name: 'sobre'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: pageTitle, name: pageTitle, widget: string }
          - { label: sectionOneTitle, name: sectionOneTitle, widget: string }
          - {
              label: sectionOneContent,
              name: sectionOneContent,
              widget: string,
            }
          - { label: sectionTwoTitle, name: sectionTwoTitle, widget: string }
          - {
              label: sectionThreeTitle,
              name: sectionThreeTitle,
              widget: string,
            }
          - { label: bylaws, name: bylaws, widget: file, default: 'static/ESTATUTO.pdf' }
          - { label: sectionFourTitle, name: sectionFourTitle, widget: string }
          - {
              label: internalPolicyLink,
              name: internalPolicyLink,
              widget: file,
              default: 'static/REGIMENTO.docx',
            }
          - { label: sectionFiveTitle, name: sectionFiveTitle, widget: string }
          - { label: phoneNumber, name: phoneNumber, widget: string }
          - { label: email, name: email, widget: string }
      - file: 'src/pages/palestras/index.md'
        label: 'Palestras'
        name: 'palestras'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: pageTitle, name: pageTitle, widget: string }
          - {
              label: Palestras do mês,
              name: current,
              widget: list,
              create: true,
              fields:
                [
                  { label: Palestra, name: palestra, widget: string },
                  { label: Palestrante, name: palestrante, widget: string },
                  { label: Data, name: data, widget: string },
                  { label: Horário, name: horario, widget: string },
                ],
            }
          - {
              label: Palestras Passadas,
              name: past,
              widget: list,
              create: true,
              fields:
                [
                  { label: Palestra, name: palestra, widget: string },
                  { label: Palestrante, name: palestrante, widget: string },
                  { label: Data, name: data, widget: string },
                  { label: Horário, name: horario, widget: string },
                ],
            }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
